"""advanced_schema_updates_v2

Revision ID: 76bdd9bc31dd
Revises: ec46aa437748
Create Date: 2026-05-02 12:15:06.643560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76bdd9bc31dd'
down_revision: Union[str, Sequence[str], None] = 'ec46aa437748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('retrieved_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_query_logs_slow', 'query_logs', ['latency_ms'], unique=False, postgresql_where=sa.text('latency_ms > 500'))
    op.create_index('ix_query_logs_tenant_id', 'query_logs', ['tenant_id'], unique=False)
    op.add_column('chunks', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('content_type', sa.String(length=50), nullable=True))
    op.add_column('chunks', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_tenant_id'), table_name='chunks')
    op.create_index('ix_chunks_tenant_doc', 'chunks', ['tenant_id', 'document_id'], unique=False)
    op.create_index('ix_chunks_tenant_index', 'chunks', ['tenant_id', 'chunk_index'], unique=False)
    op.add_column('documents', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index('ix_documents_pending', 'documents', ['tenant_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_unique_constraint('uq_documents_tenant_hash', 'documents', ['tenant_id', 'content_hash'])
    op.create_index('ix_ingestion_jobs_processing', 'ingestion_jobs', ['document_id', 'started_at'], unique=False, postgresql_where=sa.text("status = 'processing'"))
    op.add_column('tenants', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'is_active')
    op.drop_index('ix_ingestion_jobs_processing', table_name='ingestion_jobs', postgresql_where=sa.text("status = 'processing'"))
    op.drop_constraint('uq_documents_tenant_hash', 'documents', type_='unique')
    op.drop_index('ix_documents_pending', table_name='documents', postgresql_where=sa.text("status = 'pending'"))
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'content_hash')
    op.drop_column('documents', 'language')
    op.drop_column('documents', 'file_size_bytes')
    op.drop_index('ix_chunks_tenant_index', table_name='chunks')
    op.drop_index('ix_chunks_tenant_doc', table_name='chunks')
    op.create_index(op.f('ix_chunks_tenant_id'), 'chunks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.drop_column('chunks', 'content_hash')
    op.drop_column('chunks', 'content_type')
    op.drop_column('chunks', 'token_count')
    op.drop_index('ix_query_logs_tenant_id', table_name='query_logs')
    op.drop_index('ix_query_logs_slow', table_name='query_logs', postgresql_where=sa.text('latency_ms > 500'))
    op.drop_table('query_logs')
    # ### end Alembic commands ###
